env: "local"
pathology_level: 0.8
research_save_path: ./researches
http:
  host: localhost
  port: 9042
postgres:
  host: localhost
  port: 9432
  name: med
  user: postgres
  password: postgres
  migrations_dir: ./migrations
grpc:
  host: localhost
  port: 30042