env: prod
pathology_level: 0.8
research_save_path: /researches
http:
  host: 0.0.0.0
  port: 9042
postgres:
  host: postgres
  port: 5432
  name: med
  user: postgres
  password: postgres
  migrations_dir: /app/migrations
grpc:
  host: inference
  port: 30042